# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "oraclelinux/8"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"
  config.vm.hostname = "dns.localdomain"
  config.vm.network "public_network",  ip: "192.168.68.114"
  #config.vm.network "public_network", bridge: "TP-Link Wireless USB Adapter"
  config.vm.synced_folder ".", "/vagrant"

 
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
	 vb.cpus = 2
	 vb.name = "DNS_server_RAC"	
	 
   end

   config.vm.provision "shell", inline: <<-SHELL
    sh /vagrant/scripts/setup.sh
  SHELL
end